#!/bin/bash

# Description for --help
DESC="Patterns for interpreting \`diff -u' output"

# Words to highlight - extended regex ("sed -r" compatible)
# Except with the use of '^.+$' for BOLD/UNDERLINE, having overlapping colors
# is not supported and the result will be unpredictable.
BLACK=()
RED=('^-.*$')
GREEN=('^\+.*$')
YELLOW=()
BLUE=()
MAGENTA=()
CYAN=()
WHITE=()

# Bold and Underline are special case, it can be done within and around colors. Be
# aware however that the string may have embedded escape codes at this point.

# Use '^.+$' here to get bright colors everywhere...
BOLD=('^diff.*$' '^index.*$' '^.{5}---.*$' '^.{5}\+\+\+.*$' '^@.*$') # .{5} matches color escapes

UNDERLINE=()

