#!/bin/bash

# Description for --help
DESC="Patterns for Nagios-plugins (OK:/WARNING:/CRITICAL:/UNKNOWN:)"

# Words to highlight - extended regex ("sed -r" compatible)
# Except with the use of '^.+$' for BOLD, having overlapping colors is not
# supported and the result will be unpredictable.
BLACK=('UNKNOWN:.+')
RED=('CRITICAL:.+')
GREEN=('OK:.+')
YELLOW=('WARNING:.+')
BLUE=()
MAGENTA=()
CYAN=()
WHITE=()
# Use '^.+$' here to get bright colors everywhere...
BOLD=('^.+$')

# Underline is a special case, it can be done within and around colors. Be
# aware however that the string may have embedded escape codes at this point.
UNDERLINE=()

