#!/bin/bash

# Description for --help
DESC="Patterns for TAP (Test Anyting Protocol) output"

# Words to highlight - extended regex ("sed -r" compatible)
# Except with the use of '^.+$' for BOLD/UNDERLINE, having overlapping colors
# is not supported and the result will be unpredictable.
BLACK=()
RED=('^not ok [0-9]+')
GREEN=('^ok [0-9]+')
YELLOW=('^[0-9]+\.\.[0-9]+$')
BLUE=()
MAGENTA=()
CYAN=('^#.*$') # Works only when stderr is appended to stdout
WHITE=()

# Bold and Underline are special case, it can be done within and around colors. Be
# aware however that the string may have embedded escape codes at this point.

# Use '^.+$' here to get bright colors everywhere...
BOLD=('^.{5}[^#].*$') # .{5} matches color escapes

UNDERLINE=()

